services:
  rabbitMq:
    container_name: rabbitMq
    image: rabbitmq:4.1.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    container_name: redis
    image: redis:8.2
    ports:
      - "6379:6379"
