server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spotify

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    "[com.dawood.spotify]": debug

app:
  jwt:
    secret: ${JWT_SECRET}
