server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spotify

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RBMQ_PASSWORD}
    password: ${RBMQ_PASSWORD}

logging:
  level:
    root: info
    "[com.dawood.spotify]": debug

app:
  jwt:
    secret: ${JWT_SECRET}

  cloudinary:
    api-secret: ${CLOUDINARY_API_SECRET}
    api-key: ${CLOUDINARY_API_KEY}
    api-url: ${CLOUDINARY_URL}
    api-name: ${CLOUDINARY_API_NAME}

  seeder:
    super-admin-email: ${SUPER_ADMIN_EMAIL}
    super-admin-password: ${SUPER_ADMIN_PASSWORD}
