server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spotify

  servlet:
    multipart:
      max-file-size: 50MB

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    # host: localhost
    host: ${RBMQ_HOST}
    port: 5671
    username: ${RBMQ_PASSWORD}
    password: ${RBMQ_PASSWORD}
    ssl:
      enabled: true

  flyway:
    baseline-on-migrate: true

  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  # cache:
  #   type: redis

logging:
  level:
    root: info
    "[com.dawood.spotify]": debug

app:
  jwt:
    secret: ${JWT_SECRET}

  cloudinary:
    api-secret: ${CLOUDINARY_API_SECRET}
    api-key: ${CLOUDINARY_API_KEY}
    api-url: ${CLOUDINARY_URL}
    api-name: ${CLOUDINARY_API_NAME}

  seeder:
    super-admin-email: ${SUPER_ADMIN_EMAIL}
    super-admin-password: ${SUPER_ADMIN_PASSWORD}
