server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spotify

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# logging:
#   level:
#     root: info
#     "[com.dawood.spotify]": debug

app:
  jwt:
    secret: ${JWT_SECRET}
